name: Update TestFlight Link Status

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'pluwen/awesome-testflight-link'
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: python3 -m pip install httpx
      - name: Update TestFlight Link Status
        run: python3 scripts/update_status.py

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain README.md data/links.json)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add README.md data/links.json
            git commit -m "Auto-update TestFlight link status: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi

  forked-repo:
    runs-on: ubuntu-latest
    if: github.repository != 'pluwen/awesome-testflight-link'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add upstream https://github.com/pluwen/awesome-testflight-link.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main

